# Modul #2 Tapşırıqları

In [1]:
# Lazım olan kitabxanalar
import numpy as np
import warnings

In [2]:
warnings.filterwarnings(action = 'ignore')
np.random.seed(seed = 42)

***
### Tapşırıq #1
- Tək dəyərlərdən ibarət (1 dən 100-ə kimi) array data strukturu yarat

In [4]:
array = np.arange(start = 1, stop = 100, step = 2)
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

- Yaradılan həmin array data strukturunu 5 sətir və 10 sütun halına sal

In [9]:
array_reshape = array.reshape(5, 10)
array_reshape

array([[11, 47, 61, 85, 15, 81, 49, 41, 25, 27],
       [95, 59, 77,  3, 33, 35, 63, 73, 75, 23],
       [19, 69, 89, 37,  7, 13, 21, 45, 39, 87],
       [ 9, 57, 93, 67, 71, 97, 29, 91,  5, 83],
       [17, 43, 51, 99, 53, 55, 31, 79,  1, 65]])

- Array data strukturunda olan dəyərlərin sırasını random şəkildə qarışdır

In [13]:
# kodu bu şərhin altına yaz
np.random.shuffle(array)
array

array([89, 55, 25, 57,  3, 21, 59, 79, 73, 49,  7, 13, 83, 41, 77, 95, 75,
       33, 97, 69, 87, 61, 47, 19,  9, 27, 91, 35, 81, 85, 53, 37, 99, 67,
       17, 15, 65, 39, 45, 51,  1, 93,  5, 29, 31, 71, 63, 11, 23, 43])

- Array data strukturunda olan dəyərlərin sırasını əvvəlki ardıcıllığa uygun olaraq dəyişdir

In [14]:
array = np.sort(array)
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

- Array data strukturunu düzləşdir yəni ilk yaradıldığı hala qaytar

In [15]:
array = array.flatten()
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

- Array data strukturunda olan dəyərlərdən 50-dən böyük olan dəyərləri filterlə 

In [58]:
# method 2:
index = array > 50
filtered_array = array[index]       
filtered_array 

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

***
### Tapşırıq #2
- Bütün dəyərləri 0-dan ibarət olan int64 data növlü 3 sətir və 4 sütundan ibarət array yarat 

In [64]:
zeros = np.zeros(shape = (3, 4), dtype = np.int64)
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

- Bütün dəyərləri 1-dan ibarət olan int64 data növlü 3 sətir və 4 sütundan ibarət array yarat 

In [70]:
ones = np.ones(shape = (3, 4), dtype = np.int64) 
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

- Hər iki array-i vertikal şəkildə birləşdir (birləşdirmə zamanı array sırasının fərqi yoxdur)

In [81]:
combined_array = np.vstack(tup = (zeros, ones))
combined_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

- Birləşdirilən array data strukturunda olan sətirlərin sayı qədər dəyərdən ibarət olan ardıcıl şəkildə düzülmüş array yarat (0-dan başlayır ilk dəyər)

In [83]:
new_array = np.arange(combined_array.shape[0])
new_array

array([0, 1, 2, 3, 4, 5])

- Yeni yaradılan arrayin ölçüsünü dəyişərək dəyərlərin sayı qədər sətir yarat, yəni hər bir dəyər bir sətir olsun

In [85]:
new_array = new_array.reshape(-1, 1)
new_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

- Bu arrayi **combined_array**-ə horizontal şəkildə birləşdir

In [86]:
array = np.hstack(tup = (new_array, combined_array))
array

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [3, 1, 1, 1, 1],
       [4, 1, 1, 1, 1],
       [5, 1, 1, 1, 1]], dtype=int64)

- Horizontal şəkildə birləşdirilmiş array-dən unikal dəyərlərdən ibarət yeni array yarat

In [87]:
unique_array = np.unique(array)
unique_array

array([0, 1, 2, 3, 4, 5], dtype=int64)

- Unikal dəyərlərdən ibarət olan array-də 2-ə bərabər və ya böyük dəyərləri "2-ə bərabər və ya böyük" 2-dən kiçik dəyərləri isə "2-dən kiçik" kimi əvəzlə

In [88]:
array = np.where(unique_array >= 2, '2-ə bərabər və ya böyük', '2-dən kiçik')
array

array(['2-dən kiçik', '2-dən kiçik', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük', '2-ə bərabər və ya böyük',
       '2-ə bərabər və ya böyük'], dtype='<U23')

***
### Tapşırıq #3
- Dəyərləri 1-dən 24-ə kimi (24 daxildir) 4 sətir və 6 sütundan ibarət array yarat

In [97]:
array = np.arange(start = 1, stop = 25).reshape(4, 6)
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

- Array-də ilk sətirin sonuncu dəyərini və son sətrin ilk dəyərini filterlə

In [100]:
array[[0, -1], [-1, 0]]

array([ 6, 19])

- Array-də ilk sətirin və 3-cü sətirlərin son 3 dəyərini filterlə

In [104]:
array[[0, 2], -3:]

array([[ 4,  5,  6],
       [16, 17, 18]])

- Array-də bütün sətirlərin və 3-cü və 4-cü dəyərlərini filterlə

In [105]:
array[:4, [2,3]]

array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]])

- Array-də maksimum dəyəri göstər

In [107]:
np.max(array)

24

- Array-də minimum dəyəri göstər

In [108]:
np.min(array)

1

- Array-də ortalama dəyəri göstər

In [109]:
np.mean(array)

12.5

- Array-də median dəyəri göstər

In [111]:
np.median(array)

12.5

- Təsadüfi 10 integer dəyərdən ibarət, minimum ala biləcəyi dəyər 10 maksimum ala biləcəyi dəyər isə 100 ola biləcək array yarat

In [114]:
np.random.seed(seed = 42)

random_array = np.random.randint(low = 10, high = 101, size = 10)
random_array

array([61, 24, 81, 70, 30, 92, 96, 84, 84, 97])

- Bu array-də maksimum dəyərin indeksini göstər

In [117]:
random_array.argmax()

9

- Bu array-də minimum dəyərin indeksini göstər

In [118]:
np.argmin(random_array)

1

***
### Tapşırıq #4
- Dəyərləri Əsəd, Gülnar, Anar və Rəna-dan ibarət olan array yarat

In [120]:
array = np.array(object = ['Əsəd', 'Gülnar', 'Anar', 'Rəna'])
array

array(['Əsəd', 'Gülnar', 'Anar', 'Rəna'], dtype='<U6')

- Array-də olan bütün adların ilk hərfini kiçilt

In [122]:
array = np.char.lower(array)
array

array(['əsəd', 'gülnar', 'anar', 'rəna'], dtype='<U6')

- Array-də olan bütün adların bütün hərflərini böyüt

In [124]:
array = np.char.upper(array)
array

array(['ƏSƏD', 'GÜLNAR', 'ANAR', 'RƏNA'], dtype='<U6')

- Array-də olan bütün adların ilk hərfini böyük saxla qalan hərfləri kiçilt

In [126]:
array = np.char.capitalize(array)
array

array(['Əsəd', 'Gülnar', 'Anar', 'Rəna'], dtype='<U6')

- Array-də A hərfi ilə başlayan adı filterlə

In [128]:
np.char.startswith(array, prefix = 'A')

array([False, False,  True, False])

- Array-də r hərfi ilə bitən ad(ları) filterlə

In [130]:
np.char.endswith(array, suffix = 'r')

array([False,  True,  True, False])